version: '3'

services:
  geo1:
    build: .
    networks:
      - mynetwork
    container_name: geo1
    restart: always
    volumes:
      - "./public:/app/public"
  geo2:
    build: .
    networks:
      - mynetwork
    container_name: geo2
    restart: always
    volumes:
      - "./public:/app/public"
  geo3:
    build: .
    networks:
      - mynetwork
    container_name: geo3
    restart: always
    volumes:
      - "./public:/app/public"

  redis:
    image: redis
    networks:
      - mynetwork
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres
    networks:
      - mynetwork
    container_name: dbGeo
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
volumes:
  redis_data:
networks:
  mynetwork:
    external: true