version: '3'

services:
  nginx:
    image: nginx
    container_name: my-nginx-container
    networks:
      - mynetwork
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - /home/m/GolandProjects/gh_course4/go-kata/course3/2.server/5.CA/GeoserviceNginx/nginx:/var/log/nginx
    restart: always

networks:
  mynetwork:
    external: true
