{
 "title": "Geoservice dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "myapp_SearchByQuery_duration_seconds_sum"
    },
    {},
    {
     "expr": "myapp_Login_duration_seconds_sum"
    },
    {
     "expr": "myapp_Register_duration_seconds_sum"
    },
    {
     "expr": "myapp_SearchByGeo_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "myapp_SearchByGeo_total{job=\"my_web_app\"}"
    },
    { "expr": "myapp_SearchByQuery_total" },
    { "expr": "myapp_Login_total" },
    { "expr": "myapp_Register_total" }
   ]
  },
  {
   "title": "DataBase and Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "myapp_SearchByQueryDatabase_duration_seconds_sum{job=\"my_web_app\"}"
    },
    {
     "expr": "myapp_SearchByGeoCache_duration_seconds_sum{job=\"my_web_app\"}"
    },
    {
     "expr": "myapp_SearchByQueryCache_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "External API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "myapp_SearchByGeoExternal_duration_seconds_sum{job=\"my_web_app\"}"
    },
    {
     "expr": "myapp_SearchByQueryExternal_duration_seconds_sum{job=\"my_web_app\"}"
    }
   ]
  }
 ]
}