version: '3'

services:
  user:
    build: .
    networks:
      - mynetwork
    container_name: user
    restart: always
    volumes:
      - "./public:/app/public"

  db:
    image: postgres
    networks:
      - mynetwork
    container_name: dbUser
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  user-grpc:
    build: grpc/grpcUser
    networks:
      - mynetwork
    container_name: grpcUser
    restart: always
networks:
  mynetwork:
    external: true